### ISSUE TITLE
Full Codable support and version 0.9.0

### ISSUE THREAD

**Issue by novi** [novi/mysql-swift#69]
I'm planning following changes on next minor(actually major) version `0.9.0`.

- [x] Change row decoder to Swift.Decoder(Decodable) #74 #72
- [x] Implement query parameter encoder for Swift.Encodable #72 
- [x] JSON column support #85
- [x] Decimal type support #86

Current row decoder `QueryRowResultType ` and parameter type `QueryParameterDictionaryType` will be deprecated or support dropped.

And will maintain `0.8.x` for a period of time on [0.8-branch](https://github.com/novi/mysql-swift/tree/0.8-branch).

Related #58 #68.

**Comment by novi** [comment]
Released `0.9.0-beta.1` with Codable support.

**Comment by florianreinhart** [comment]
This is awesome! I'll try to test it asap.

**Comment by florianreinhart** [comment]
@novi 0.9.0 works great for me. Just two issues I ran into:

* Nested JSON support ist missing (but you already know that). I currently work around this by decoding a `Data` instance in my types and manually create a JSONDecoder.
* Foundation's `Decimal` encodes and decodes itself as a dictionary, aka keyed container. We need to manually decode a decimal from MySQL using `Decimal(init:locale:)`. See: https://github.com/apple/swift-corelibs-foundation/blob/b41506ce7918f4b5eff7374045dc319c896db8af/Foundation/Decimal.swift#L2099

**Comment by novi** [comment]
@florianreinhart These issues will be fixed in #85, #86.

**Comment by novi** [comment]
Released `0.9.0-beta.6`, includes #85, #86 and various bug fixes.

**Comment by novi** [comment]
Released [0.9.0](https://github.com/novi/mysql-swift/releases/tag/0.9.0).
